name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todo dia às 00:00 UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: Assets/metrics.plugin.activity.svg
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 7
          plugin_activity_filter: push, issue, pr, release, fork, review, ref/create
